name: pos_renting_v3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  auto_size_text: ^3.0.0
  curved_navigation_bar: ^1.0.6
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  intl: ^0.20.1
  liquid_swipe: ^3.1.0
  provider: ^6.1.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
